/**
 * /read/ — the text edition of The Memory Atlas, prerendered from data/atlas-data.js.
 *
 * Why it exists (v2.0.0): the 3D app keeps all of its content inside JS constants,
 * so crawlers saw a title and a canvas, phones got a "built for desktop" sheet,
 * and a WebGL failure meant nothing. These are plain, fast, static pages of the
 * SAME content — every node file, every company, the four investor views, and
 * the 26-stop journey as an ordered reading list — each linking back into the 3D
 * atlas by deep link. Regenerated by `npm run build`; never hand-edit read/*.html.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'read');
const SITE = 'https://memory.upamanyuacharya.com';
const D = await import(pathToFileURL(path.join(ROOT, 'data', 'atlas-data.js')).href);
const { CO, COURL, HIER, EXTRA, ELI, SRC, WATCH_GROUPS, ROADMAP, GEO, SHORTLIST, JOURNEY, REGIONS, DATA_ASOF, MODELS, SERVING, KV_DEFAULT } = D;

/* ---------- helpers ---------- */
const nodes = HIER.concat(Object.values(EXTRA));
const findNode = id => nodes.find(n => n.id === id) || null;
const backlinks = cid => nodes.filter(n => n.cos && n.cos.includes(cid));
const nodeSev = cid => { const l = backlinks(cid); return l.length ? Math.max(...l.map(n => n.sev || 0)) : 0; };
const sevWord = s => ['—', 'Low', 'Moderate', 'High', 'Severe', 'Critical'][s] || '—';
const sevColor = s => s >= 5 ? '#ff5d6c' : s >= 4 ? '#f6a345' : s >= 3 ? '#f5d76e' : s >= 2 ? '#5eead4' : '#7d8aa3';
const R2SLUG = { map: 'map', hierarchy: 'stack', cxl: 'cxl', photonics: 'photonics', kvcache: 'kvcache', ai: 'wall' };
const REGION_NAME = { map: 'The Map', hierarchy: 'The Memory Stack', cxl: 'The CXL Fabric', photonics: 'Photonics', kvcache: 'The KV Cache', ai: 'The Memory Wall' };
const nodeRegion = id => { const s = JOURNEY.find(x => x.n === id); if (s) return s.r; if (HIER.some(h => h.id === id)) return 'hierarchy'; if (id.startsWith('cxl')) return 'cxl'; if (id.startsWith('phot')) return 'photonics'; if (id.startsWith('kv')) return 'kvcache'; return 'map'; };
const strip = s => String(s || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
const esc = s => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const asofLabel = () => new Date(DATA_ASOF + 'T00:00:00Z').toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
const priv = co => co.tk === 'PRIVATE' || co.tk.startsWith('→');
const journeyIndex = id => JOURNEY.findIndex(s => s.n === id);
const stopLink = s => s.intel ? `investor.html#${s.intel}` : s.n ? `${s.n}.html` : `../#${R2SLUG[s.r]}`;

/* ---------- chrome ---------- */
const CSS = `
:root{--bg:#060709;--ink:#eef2f8;--dim:#a7b3c6;--faint:#6f7c93;--hair:rgba(255,255,255,.09);--hair2:rgba(255,255,255,.18);--accent:#5eead4;--violet:#9a8cff;--gold:#f5d76e;--glass:rgba(255,255,255,.035);--display:'Space Grotesk',system-ui,sans-serif;--body:'Geist',system-ui,sans-serif;--mono:'Geist Mono',ui-monospace,monospace}
*{box-sizing:border-box}html{color-scheme:dark}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--body);font-size:18px;line-height:1.7;-webkit-font-smoothing:antialiased}
a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}
.wrap{max-width:760px;margin:0 auto;padding:28px 22px 96px}
header.top{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:34px}
.brand{font-family:var(--display);font-weight:600;font-size:20px;letter-spacing:-.01em;color:var(--ink)}.brand i{font-style:italic;font-weight:500;color:var(--accent)}
.brand small{display:block;font-family:var(--mono);font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:var(--faint);margin-top:3px}
.cta{display:inline-flex;align-items:center;gap:8px;font-family:var(--mono);font-size:12px;letter-spacing:.06em;color:#06110f;background:var(--accent);border-radius:999px;padding:10px 16px;font-weight:600}.cta:hover{text-decoration:none;filter:brightness(1.08)}
.cta.ghost{background:var(--glass);color:var(--ink);border:1px solid var(--hair2)}
.crumbs{font-family:var(--mono);font-size:12px;letter-spacing:.05em;color:var(--faint);margin-bottom:18px}.crumbs a{color:var(--dim)}
.kmini{font-family:var(--mono);font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:var(--faint);margin:34px 0 10px}
h1{font-family:var(--display);font-size:clamp(34px,6vw,50px);font-weight:600;letter-spacing:-.025em;line-height:1.04;margin:6px 0 10px}
h2{font-family:var(--display);font-size:28px;font-weight:600;letter-spacing:-.02em;line-height:1.15;margin:44px 0 12px}
h3{font-family:var(--display);font-size:20px;font-weight:600;margin:22px 0 6px}
p{margin:0 0 16px}b{color:var(--ink)}em{color:var(--ink);font-style:italic}.hl2{color:var(--gold)}
.tier{font-family:var(--mono);font-size:11px;letter-spacing:.2em;text-transform:uppercase;display:inline-flex;align-items:center;gap:8px}.tier .dot{width:8px;height:8px;border-radius:50%;box-shadow:0 0 12px currentColor;background:currentColor}
.tag{font-family:var(--mono);font-size:14px;color:var(--dim);margin-bottom:22px}
.lede{font-size:21px;line-height:1.55;color:#d7dfeb}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin:18px 0 6px}
.stat{background:var(--glass);border:1px solid var(--hair);border-radius:12px;padding:12px 14px}.stat .l{font-family:var(--mono);font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:var(--faint)}.stat .v{font-family:var(--display);font-size:17px;font-weight:600;margin-top:4px;color:var(--ink)}
.blk{background:var(--glass);border:1px solid var(--hair);border-radius:14px;padding:18px 20px;margin:14px 0}.blk .kmini{margin:0 0 8px}.blk p:last-child{margin-bottom:0}
.blk.eli{border-color:rgba(94,234,212,.28)}.blk.jour{border-color:rgba(154,140,255,.35)}
.sev{display:flex;align-items:center;gap:10px;margin:6px 0 10px}.sev .bars{display:flex;gap:4px}.sev .bars i{width:22px;height:8px;border-radius:3px;display:block}.sev .lbl{font-family:var(--mono);font-size:12px;letter-spacing:.1em;text-transform:uppercase}
.share{display:flex;height:14px;border-radius:7px;overflow:hidden;margin:10px 0 8px}.share i{display:block;height:100%}.leg{display:flex;flex-wrap:wrap;gap:6px 16px;font-family:var(--mono);font-size:12px;color:var(--dim)}.leg i{display:inline-block;width:9px;height:9px;border-radius:2px;margin-right:6px;vertical-align:middle}
ul.plain{list-style:none;padding:0;margin:0}ul.plain li{padding:10px 0;border-top:1px solid var(--hair)}ul.plain li:first-child{border-top:0}
.mk{font-family:var(--display);font-weight:600;color:var(--ink)}.mv{color:var(--dim);font-size:16.5px}
.geo{display:flex;gap:14px;padding:9px 0;border-top:1px solid var(--hair)}.geo:first-child{border-top:0}.geo .cc{font-family:var(--mono);font-size:12px;letter-spacing:.1em;color:var(--accent);min-width:64px;padding-top:4px}
.co{display:grid;grid-template-columns:52px 1fr;gap:14px;padding:16px 0;border-top:1px solid var(--hair)}.co:first-child{border-top:0}
.logo{width:52px;height:52px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-family:var(--display);font-weight:700;font-size:15px;letter-spacing:.02em;overflow:hidden;background:#1a2233;color:#bcd6ff}.logo img{width:100%;height:100%;object-fit:cover}
.co h3{margin:0 0 2px}.co .tk{font-family:var(--mono);font-size:12px;color:var(--faint);margin-left:6px}.co .tk.priv{color:var(--violet)}.co .makes{font-family:var(--mono);font-size:13px;color:var(--dim);margin-bottom:6px}.co p{font-size:16.5px;margin-bottom:8px}
.pills{display:flex;flex-wrap:wrap;gap:6px;margin:6px 0}.pill{font-family:var(--mono);font-size:12px;color:var(--dim);border:1px solid var(--hair2);border-radius:999px;padding:4px 10px;background:var(--glass)}.pill.link:hover{border-color:var(--accent);text-decoration:none;color:var(--ink)}
.rel{display:flex;flex-wrap:wrap;gap:8px}.rel a{display:inline-flex;align-items:center;gap:8px;font-family:var(--mono);font-size:13px;color:var(--ink);border:1px solid var(--hair2);border-radius:999px;padding:7px 13px;background:var(--glass)}.rel a:hover{text-decoration:none;border-color:var(--accent)}.rel .d{width:8px;height:8px;border-radius:50%}
.src a{display:block;padding:9px 0;border-top:1px solid var(--hair);font-size:16px}.src a:first-child{border-top:0}
nav.pn{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:48px 0 0}nav.pn a{display:block;background:var(--glass);border:1px solid var(--hair);border-radius:14px;padding:14px 16px;color:var(--ink)}nav.pn a:hover{border-color:var(--accent);text-decoration:none}nav.pn small{display:block;font-family:var(--mono);font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--faint);margin-bottom:5px}nav.pn .next{text-align:right}
ol.journey{list-style:none;padding:0;margin:0;counter-reset:s}ol.journey li{display:grid;grid-template-columns:44px 1fr;gap:12px;padding:16px 0;border-top:1px solid var(--hair)}ol.journey li:first-child{border-top:0}
ol.journey .n{font-family:var(--mono);font-size:13px;color:var(--faint);padding-top:5px}ol.journey .t{font-family:var(--display);font-size:20px;font-weight:600;line-height:1.25}ol.journey .r{font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--faint);margin:2px 0 6px}ol.journey p{font-size:16.5px;color:var(--dim);margin:0}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:10px}.grid a{display:block;background:var(--glass);border:1px solid var(--hair);border-radius:12px;padding:12px 14px;color:var(--ink);font-family:var(--display);font-weight:600;font-size:16px;line-height:1.3}.grid a small{display:block;font-family:var(--mono);font-weight:400;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:var(--faint);margin-top:4px}.grid a:hover{border-color:var(--accent);text-decoration:none}
.tl{border-left:2px solid var(--hair2);padding-left:22px;margin:8px 0 0}.tl .it{position:relative;padding:4px 0 26px}.tl .it:before{content:'';position:absolute;left:-29px;top:12px;width:12px;height:12px;border-radius:50%;background:var(--dotc);box-shadow:0 0 14px var(--dotc)}.tl .d{font-family:var(--mono);font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--dim)}.tl .d span{margin-left:10px;color:var(--faint)}.tl .t{font-family:var(--display);font-size:21px;font-weight:600;margin:4px 0 6px}.tl p{font-size:16.5px;color:var(--dim)}
.verdict{display:inline-block;font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;border-radius:999px;padding:3px 10px;margin-left:8px;border:1px solid}.verdict.hit{color:#7ee787;border-color:#7ee787}.verdict.partial{color:#f5d76e;border-color:#f5d76e}.verdict.miss{color:#ff5d6c;border-color:#ff5d6c}.verdict.open{color:var(--faint);border-color:var(--hair2)}
.asof{font-family:var(--mono);font-size:12px;color:var(--faint);border:1px dashed var(--hair2);border-radius:999px;padding:6px 12px;display:inline-block}
footer{margin-top:64px;padding-top:22px;border-top:1px solid var(--hair);font-family:var(--mono);font-size:12px;color:var(--faint);line-height:1.8}footer a{color:var(--dim)}
table{width:100%;border-collapse:collapse;font-size:15px}th,td{text-align:left;padding:9px 8px;border-top:1px solid var(--hair);vertical-align:top}th{font-family:var(--mono);font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:var(--faint);border-top:0}td.num{font-family:var(--mono);text-align:right;white-space:nowrap}.tbl{overflow-x:auto;margin:10px 0}
@media (max-width:600px){body{font-size:17px}.wrap{padding:20px 16px 80px}nav.pn{grid-template-columns:1fr}nav.pn .next{text-align:left}.co{grid-template-columns:44px 1fr}.logo{width:44px;height:44px}}
`;

function logo(co, id) {
  if (co.ic) return `<span class="logo"><img src="../${co.ic}" alt="" loading="lazy" width="52" height="52"></span>`;
  const h = [...co.n].reduce((a, c) => (a * 31 + c.charCodeAt(0)) % 360, 0);
  const init = co.n.split(/\s+/).map(w => w[0]).join('').slice(0, 3).toUpperCase();
  return `<span class="logo" style="background:linear-gradient(140deg,hsl(${h},44%,24%),hsl(${(h + 24) % 360},40%,17%));color:hsl(${h},78%,80%)">${init}</span>`;
}

function page({ file, title, desc, body, crumbs, jsonld, ogTitle }) {
  const url = `${SITE}/read/${file === 'index.html' ? '' : file}`;
  const crumbHtml = crumbs ? `<div class="crumbs">${crumbs.map(([t, h]) => h ? `<a href="${h}">${t}</a>` : t).join(' <span style="opacity:.5">/</span> ')}</div>` : '';
  const ld = { '@context': 'https://schema.org', '@type': 'Article', headline: strip(title), description: strip(desc), url, dateModified: DATA_ASOF, inLanguage: 'en',
    author: { '@type': 'Person', name: 'Upamanyu Acharya', url: 'https://upamanyuacharya.com' }, isPartOf: { '@type': 'WebSite', name: 'The Memory Atlas', url: SITE + '/' }, image: `${SITE}/assets/og.png`, ...(jsonld || {}) };
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(strip(title))} — The Memory Atlas</title>
<meta name="description" content="${esc(strip(desc)).slice(0, 300)}">
<link rel="canonical" href="${url}">
<meta name="theme-color" content="#060709">
<meta property="og:type" content="article"><meta property="og:site_name" content="The Memory Atlas"><meta property="og:url" content="${url}">
<meta property="og:title" content="${esc(strip(ogTitle || title))}"><meta property="og:description" content="${esc(strip(desc)).slice(0, 200)}">
<meta property="og:image" content="${SITE}/assets/og.png"><meta property="og:image:width" content="1280"><meta property="og:image:height" content="720">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(strip(ogTitle || title))}"><meta name="twitter:description" content="${esc(strip(desc)).slice(0, 200)}"><meta name="twitter:image" content="${SITE}/assets/og.png">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%23060709'/%3E%3Ccircle cx='16' cy='16' r='8' fill='none' stroke='%235eead4' stroke-width='2.4'/%3E%3Ccircle cx='16' cy='16' r='2.6' fill='%235eead4'/%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Geist:wght@400;500;600&family=Geist+Mono:wght@400;500&display=swap" rel="stylesheet">
<script type="application/ld+json">${JSON.stringify(ld).replace(/</g, '\\u003c')}</script>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BQ35RMCCW9"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-BQ35RMCCW9",{page_title:document.title});</script>
<style>${CSS}</style>
</head>
<body><div class="wrap">
<header class="top"><a class="brand" href="./">The Memory <i>Atlas</i><small>Text edition</small></a><a class="cta" href="../">▶&nbsp; Open the 3D atlas</a></header>
${crumbHtml}
${body}
<footer>Every fact here was re-verified against primary sources on <b>${asofLabel()}</b>. Educational structural analysis, not investment advice.<br>
Built by <a href="https://upamanyuacharya.com">Upamanyu Acharya</a> · <a href="https://github.com/upamanyuacharya/memory-atlas">open source on GitHub</a> · <a href="./">text edition index</a> · <a href="../">3D atlas</a></footer>
</div></body></html>
`;
}

/* ---------- node pages ---------- */
function nodePage(node) {
  const id = node.id, r = nodeRegion(id), ji = journeyIndex(id);
  const stop = ji >= 0 ? JOURNEY[ji] : null;
  const tagLine = node.cap ? `${node.cap} · ${node.bw} · ${node.lat}` : node.kind;
  let b = '';
  b += `<div class="tier" style="color:${node.col}"><span class="dot"></span>${esc(node.kind)}</div>`;
  b += `<h1>${node.name}</h1><div class="tag">${esc(tagLine)}</div>`;
  b += `<p><a class="cta" href="../#node/${id}">▶&nbsp; See it in 3D</a> &nbsp; <a class="cta ghost" href="../#${R2SLUG[r]}">${REGION_NAME[r]} region</a></p>`;
  if (stop && stop.cap) b += `<div class="blk jour"><div class="kmini" style="color:var(--violet)">On the journey · stop ${ji + 1} of ${JOURNEY.length}</div><p>${stop.cap}</p></div>`;
  if (node.stats) b += `<div class="stats">${node.stats.map(s => `<div class="stat"><div class="l">${esc(s[0])}</div><div class="v">${esc(s[1])}</div></div>`).join('')}</div>`;
  else b += `<div class="stats"><div class="stat"><div class="l">Capacity</div><div class="v">${esc(node.cap)}</div></div><div class="stat"><div class="l">Bandwidth</div><div class="v">${esc(node.bw)}</div></div><div class="stat"><div class="l">Latency</div><div class="v">${esc(node.lat)}</div></div><div class="stat"><div class="l">Energy</div><div class="v">${esc(node.en)}</div></div></div>`;
  if (ELI[id]) b += `<div class="blk eli"><div class="kmini">In plain English</div><p class="lede">${ELI[id]}</p></div>`;
  b += `<h2>What it is</h2><p>${node.blurb}</p>`;
  b += `<h2>The business</h2><p>${node.biz}</p>`;
  if (node.share) b += `<div class="blk"><div class="kmini">${esc(node.share.title)}</div><div class="share">${node.share.seg.map(s => `<i style="flex:${s[1]};background:${s[2]}"></i>`).join('')}</div><div class="leg">${node.share.seg.map(s => `<span><i style="background:${s[2]}"></i>${esc(s[0])} ${s[1]}%</span>`).join('')}</div></div>`;
  b += `<h2>Bottleneck severity</h2><div class="sev"><div class="bars">${[1, 2, 3, 4, 5].map(i => `<i style="background:${i <= node.sev ? sevColor(node.sev) : 'rgba(255,255,255,.08)'}"></i>`).join('')}</div><span class="lbl" style="color:${sevColor(node.sev)}">${sevWord(node.sev)}</span></div>`;
  if (node.why) b += `<div class="kmini" style="margin-top:6px;color:${sevColor(node.sev)}">${node.sev >= 3 ? 'Where the chokepoint comes from' : "Why it's not a chokepoint"}</div><p>${node.why}</p>`;
  if (node.cos && node.cos.length) {
    b += `<h2>Who makes it</h2><div>` + node.cos.map(cid => { const co = CO[cid]; if (!co) return ''; return `<div class="co" id="${cid}">${logo(co, cid)}<div><h3><a href="companies.html#${cid}">${esc(co.n)}</a><span class="tk ${priv(co) ? 'priv' : ''}">${esc(co.tk)}</span></h3><div class="makes">${esc(co.makes)} · ${esc(co.ctry)}</div><p>${co.role}</p><div class="pills">${co.mx.map(m => `<span class="pill">${esc(m)}</span>`).join('')}</div>${COURL[cid] ? `<a href="${COURL[cid]}" rel="noopener noreferrer" target="_blank">↗ Investor relations &amp; news</a>` : ''}</div></div>`; }).join('') + `</div>`;
  }
  if (node.mx && node.mx.length) b += `<h2>Metrics that move this layer</h2><ul class="plain">${node.mx.map(m => `<li><div class="mk">${m[0]}</div><div class="mv">${m[1]}</div></li>`).join('')}</ul>`;
  if (node.geo && node.geo.length) b += `<h2>Where it comes from</h2><div>${node.geo.map(g => `<div class="geo"><span class="cc">${esc(g[0])}</span><span>${g[1]}</span></div>`).join('')}</div>`;
  if (node.related && node.related.length) b += `<h2>Connected to</h2><div class="rel">${node.related.map(rid => { const t = findNode(rid); const reg = REGIONS[rid]; const nm = t ? t.name : reg ? reg.name : rid; const cc = t ? t.col : reg ? reg.col : '#888'; const href = t ? `${rid}.html` : reg ? `../#${R2SLUG[reg.into]}` : '#'; return `<a href="${href}"><span class="d" style="background:${cc}"></span>${esc(nm)}</a>`; }).join('')}</div>`;
  if (SRC[id]) b += `<h2>Further reading</h2><div class="src">${SRC[id].map(s => `<a href="${s[1]}" rel="noopener noreferrer" target="_blank">${esc(s[0])} ↗</a>`).join('')}</div>`;
  // prev / next along the journey (node stops only)
  const nodeStops = JOURNEY.map((s, i) => ({ s, i })).filter(x => x.s.n);
  const k = nodeStops.findIndex(x => x.s.n === id);
  if (k >= 0) {
    const prev = nodeStops[k - 1], next = nodeStops[k + 1];
    b += `<nav class="pn">${prev ? `<a href="${prev.s.n}.html"><small>← Previous · stop ${prev.i + 1}</small>${esc(prev.s.t)}</a>` : `<a href="./"><small>← Index</small>All files</a>`}${next ? `<a class="next" href="${next.s.n}.html"><small>Next · stop ${next.i + 1} →</small>${esc(next.s.t)}</a>` : `<a class="next" href="investor.html"><small>Next →</small>Investor Intelligence</a>`}</nav>`;
  }
  return page({ file: `${id}.html`, title: node.name, ogTitle: `${node.name} — ${strip(node.kind)}`, desc: ELI[id] || node.blurb, body: b, crumbs: [['Text edition', './'], [REGION_NAME[r], `./#${R2SLUG[r]}`], [node.name]],
    jsonld: { about: strip(node.kind), keywords: [node.name, ...(node.cos || []).map(c => CO[c] && CO[c].n).filter(Boolean)].join(', ') } });
}

/* ---------- companies ---------- */
function companiesPage() {
  const order = WATCH_GROUPS.flatMap(g => g.ids).concat(Object.keys(CO).filter(c => !WATCH_GROUPS.some(g => g.ids.includes(c))));
  const seen = new Set();
  let b = `<h1>Every company in the atlas</h1><p class="lede">${Object.keys(CO).length} names, grouped by where they sit in the chain. Each one lists what it makes, the metrics to watch, and every file in the atlas it appears in.</p><p><span class="asof">Data as of ${asofLabel()}</span></p>`;
  for (const g of WATCH_GROUPS) {
    b += `<h2>${esc(g.t)}</h2>`;
    for (const cid of g.ids) { if (seen.has(cid) || !CO[cid]) continue; seen.add(cid); b += coBlock(cid); }
  }
  const rest = order.filter(c => !seen.has(c) && CO[c]);
  if (rest.length) { b += `<h2>Also in the atlas</h2>`; for (const cid of rest) { seen.add(cid); b += coBlock(cid); } }
  return page({ file: 'companies.html', title: 'Companies', desc: 'Every company in the AI memory and interconnect supply chain covered by The Memory Atlas: what each makes, where, the metrics to watch, and which layers it touches.', body: b, crumbs: [['Text edition', './'], ['Companies']] });
}
function coBlock(cid) {
  const co = CO[cid], links = backlinks(cid), sv = nodeSev(cid);
  return `<div class="co" id="${cid}">${logo(co, cid)}<div><h3>${esc(co.n)}<span class="tk ${priv(co) ? 'priv' : ''}">${esc(co.tk)}</span></h3><div class="makes">${esc(co.makes)} · ${esc(co.ctry)} · <span style="color:${sevColor(sv)}">chokepoint ${sevWord(sv).toLowerCase()}</span></div><p>${co.role}</p><div class="kmini" style="margin:8px 0 4px">Watch</div><div class="pills">${co.mx.map(m => `<span class="pill">${esc(m)}</span>`).join('')}</div>${links.length ? `<div class="kmini" style="margin:10px 0 6px">Where it shows up · ${links.length}</div><div class="rel">${links.map(l => `<a href="${l.id}.html"><span class="d" style="background:${l.col}"></span>${esc(l.name)}</a>`).join('')}</div>` : ''}${COURL[cid] ? `<p style="margin-top:10px"><a href="${COURL[cid]}" rel="noopener noreferrer" target="_blank">↗ Investor relations &amp; news</a></p>` : ''}</div></div>`;
}

/* ---------- investor ---------- */
function investorPage() {
  const chip = cid => { const co = CO[cid]; if (!co) return ''; return `<a class="pill link" href="companies.html#${cid}">${esc(co.n)} <span style="color:var(--faint)">${esc(co.tk)}</span></a>`; };
  let b = `<h1>Investor Intelligence</h1><p class="lede">The money is structural, not a sidebar. Four views of the same map: the names that define it, every ticker by layer, where the single points of failure live, and what ships when.</p><p><span class="asof">Data as of ${asofLabel()}</span> &nbsp; <a class="cta ghost" href="../#intel/short">Open in the 3D atlas</a></p>`;
  b += `<h2 id="short">The shortlist</h2><p>The names that structurally define the map — chokepoint monopolies, scale players and pure-plays — and exactly why each one matters.</p>`;
  for (const g of SHORTLIST) { b += `<h3>${esc(g.t)}</h3><p style="color:var(--dim);font-size:16.5px">${g.d}</p><ul class="plain">${g.items.map(([cid, why]) => { const co = CO[cid]; if (!co) return ''; return `<li><div class="mk"><a href="companies.html#${cid}">${esc(co.n)}</a> <span class="tk" style="font-family:var(--mono);font-size:12px;color:var(--faint)">${esc(co.tk)}</span> <span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${sevColor(nodeSev(cid))};margin-left:6px"></span></div><div class="mv">${why}</div></li>`; }).join('')}</ul>`; }
  b += `<h2 id="watch">Every ticker, by layer</h2><p>Grouped by where each company sits in the chain. The dot is the worst chokepoint severity of any layer it touches.</p>`;
  for (const g of WATCH_GROUPS) b += `<h3>${esc(g.t)}</h3><div class="pills">${g.ids.map(chip).join('')}</div>`;
  b += `<h2 id="geo">Where the single points of failure live</h2><p>Where each critical step physically happens, ordered by single-point-of-failure risk.</p>`;
  for (const g of GEO) b += `<div class="blk"><div class="kmini" style="color:var(--accent)">${esc(g.cc)} · ${esc(g.country)}${g.sev >= 5 ? ' · <span style="color:#ff5d6c">single point of failure</span>' : ''}</div><div class="sev"><div class="bars">${[1, 2, 3, 4, 5].map(i => `<i style="background:${i <= g.sev ? sevColor(g.sev) : 'rgba(255,255,255,.08)'}"></i>`).join('')}</div><span class="lbl" style="color:${sevColor(g.sev)}">${sevWord(g.sev)}</span></div><p>${g.role}</p><div class="pills">${g.cos.map(chip).join('')}</div></div>`;
  b += `<h2 id="road">The roadmap — and the scorecard</h2><p>What happens when, and who benefits. Entries whose date has passed carry a verdict: the atlas grades its own forecasts.</p><div class="tl">`;
  for (const m of ROADMAP) {
    const v = m.v ? `<span class="verdict ${m.v.k}">${esc(m.v.t)}</span>` : '';
    b += `<div class="it" style="--dotc:${m.c}"><div class="d">${esc(m.y)}<span>${esc(m.k)}</span></div><div class="t">${m.t}${v}</div><p>${m.d}</p>${m.v && m.v.d ? `<p style="color:var(--ink);font-size:16px"><b style="color:${m.v.k === 'hit' ? '#7ee787' : m.v.k === 'miss' ? '#ff5d6c' : '#f5d76e'}">What actually happened —</b> ${m.v.d}</p>` : ''}<div class="pills">${m.cos.map(chip).join('')}</div></div>`;
  }
  b += `</div>`;
  if (D.VALUATION && D.VALUATION.rows && D.VALUATION.rows.length) {
    const V = D.VALUATION;
    b += `<h2 id="numbers">The numbers — what the market already prices in</h2><p>${V.note}</p><div class="tbl"><table><thead><tr><th>Company</th><th>Ticker</th><th style="text-align:right">Price</th><th style="text-align:right">Mkt cap</th><th style="text-align:right">12-mo</th><th style="text-align:right">Fwd P/E</th></tr></thead><tbody>`;
    for (const r of V.rows) { const co = CO[r.id]; b += `<tr><td><a href="companies.html#${r.id}">${esc(co ? co.n : r.id)}</a></td><td style="font-family:var(--mono);font-size:13px;color:var(--faint)">${esc(r.ticker)}</td><td class="num">${esc(r.price || 'n/a')}</td><td class="num">${r.mcapB == null ? 'n/a' : '$' + (r.mcapB >= 1000 ? (r.mcapB / 1000).toFixed(2) + 'T' : Math.round(r.mcapB) + 'B')}</td><td class="num" style="color:${r.ret12m == null ? 'var(--faint)' : r.ret12m >= 0 ? '#7ee787' : '#ff5d6c'}">${r.ret12m == null ? 'n/a' : (r.ret12m >= 0 ? '+' : '') + Math.round(r.ret12m) + '%'}</td><td class="num">${r.fwdPE == null ? 'n/a' : r.fwdPE.toFixed(1) + '×'}</td></tr>`; }
    b += `</tbody></table></div><p style="font-family:var(--mono);font-size:12px;color:var(--faint)">Snapshot ${esc(V.asof)} · ${esc(V.source)} · FX ${esc(V.fx)}. n/a = could not be verified from two sources, so it is left blank rather than guessed.</p>`;
  }
  return page({ file: 'investor.html', title: 'Investor Intelligence', desc: 'The shortlist, every ticker by layer, country risk and the 2025→2030 roadmap for the AI memory and interconnect supply chain — with the atlas grading its own past forecasts.', body: b, crumbs: [['Text edition', './'], ['Investor Intelligence']] });
}

/* ---------- index ---------- */
function indexPage() {
  let b = `<h1>The chips behind AI, <i style="color:var(--accent);font-style:italic">as text.</i></h1>`;
  b += `<p class="lede">Every file in <a href="../">The Memory Atlas</a> — the 3D map of the AI memory supply chain — as plain, fast pages. Same facts, same journey, no WebGL required. Read it here on a phone; open any file in 3D when you're at a desk.</p>`;
  b += `<p><span class="asof">Data as of ${asofLabel()}</span></p>`;
  b += `<div class="kmini">The journey · ${JOURNEY.length} stops, zero to expert</div><ol class="journey">`;
  JOURNEY.forEach((s, i) => {
    const href = stopLink(s);
    const where = s.intel ? 'Investor Intelligence' : REGION_NAME[s.r];
    const ext = !s.n && !s.intel;
    b += `<li><div class="n">${String(i + 1).padStart(2, '0')}</div><div><div class="t"><a href="${href}">${esc(s.t)}${ext ? ' <span style="color:var(--faint);font-weight:400">↗ 3D</span>' : ''}</a></div><div class="r">${where}</div>${s.cap ? `<p>${s.cap}</p>` : ''}</div></li>`;
  });
  b += `</ol>`;
  const byRegion = {};
  for (const n of nodes) (byRegion[nodeRegion(n.id)] ||= []).push(n);
  for (const r of ['ai', 'kvcache', 'hierarchy', 'cxl', 'photonics']) {
    if (!byRegion[r]) continue;
    b += `<h2 id="${R2SLUG[r]}">${REGION_NAME[r]} <a class="pill link" style="vertical-align:middle;margin-left:8px" href="../#${R2SLUG[r]}">open in 3D ↗</a></h2><div class="grid">${byRegion[r].map(n => `<a href="${n.id}.html">${esc(n.name)}<small>${esc(strip(n.kind))}</small></a>`).join('')}</div>`;
  }
  b += `<h2>The money</h2><div class="grid"><a href="investor.html#short">The shortlist<small>who structurally matters</small></a><a href="investor.html#watch">Every ticker, by layer<small>${Object.values(CO).filter(c => !priv(c)).length} public names</small></a><a href="investor.html#geo">Country risk<small>${GEO.length} countries, ranked</small></a><a href="investor.html#numbers">The numbers<small>market cap, 12-mo, fwd P/E</small></a><a href="investor.html#road">Roadmap &amp; scorecard<small>2025 → 2030, graded</small></a><a href="companies.html">All companies<small>${Object.keys(CO).length} files with backlinks</small></a><a href="wall.html">The Wall calculator<small>what a chat costs in GPUs</small></a></div>`;
  return page({ file: 'index.html', title: 'Text edition', ogTitle: 'The Memory Atlas — text edition', desc: 'Every file in The Memory Atlas as plain, fast pages: the memory hierarchy, HBM, CXL, photonics, the KV cache and the memory wall — who makes what, the chokepoints, and who to watch.', body: b,
    jsonld: { '@type': 'CollectionPage' } });
}

/* ---------- write ---------- */
export async function buildRead({ check = false } = {}) {
  const pages = [];
  for (const n of nodes) pages.push([`${n.id}.html`, nodePage(n)]);
  pages.push(['companies.html', companiesPage()]);
  pages.push(['investor.html', investorPage()]);
  pages.push(['index.html', indexPage()]);
  // optional extra pages registered by other generators (the Wall calculator)
  try { const { wallPage } = await import(pathToFileURL(path.join(ROOT, 'tools', 'wall.mjs')).href); pages.push(['wall.html', wallPage({ page, CSS, esc, strip, asofLabel, MODELS, SERVING, KV_DEFAULT, SITE })]); } catch (e) { if (e.code !== 'ERR_MODULE_NOT_FOUND') throw e; }
  // sitemap: every read page (no fragment URLs — crawlers drop them; the 3D routes have no crawlable body)
  const urls = [`${SITE}/`, `${SITE}/read/`, ...pages.filter(([f]) => f !== 'index.html').map(([f]) => `${SITE}/read/${f}`)];
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u => `  <url><loc>${u}</loc><lastmod>${DATA_ASOF}</lastmod></url>`).join('\n')}\n</urlset>\n`;
  const managed = new Set(pages.map(([f]) => f));
  const stray = fs.existsSync(OUT) ? fs.readdirSync(OUT).filter(f => f.endsWith('.html') && !managed.has(f)) : [];
  if (check) {
    for (const [f, html] of pages) { const p = path.join(OUT, f); if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== html) { console.error(`read/${f} is stale — run \`npm run build\``); process.exit(1); } }
    const sm = path.join(ROOT, 'sitemap.xml');
    if (!fs.existsSync(sm) || fs.readFileSync(sm, 'utf8') !== sitemap) { console.error('sitemap.xml is stale — run `npm run build`'); process.exit(1); }
    if (stray.length) { console.error(`obsolete generated pages in read/: ${stray.join(', ')} — run \`npm run build\``); process.exit(1); }
    return pages.length;
  }
  fs.mkdirSync(OUT, { recursive: true });
  for (const [f, html] of pages) fs.writeFileSync(path.join(OUT, f), html);
  for (const f of stray) { fs.unlinkSync(path.join(OUT, f)); console.log(`read/${f}: removed (no longer in the data)`); }
  fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);
  return pages.length;
}
